version: '2'

services:
    db-postgres:
        build: docker/postgres
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        user: "${UID}:${GID}"
        ports:
            - "5433:5432"
        expose:
            - 5433
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
